baseURL = "https://blog.namuori.net"
languageCode = "en-us"
title = "나무오리"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]

  author = "Kim Yu Seok"
  github = "NAMUORI00"
  Description = "I love github fork"

  headerIcon = "https://raw.githubusercontent.com/NAMUORI00/Blog/main/static/images/github-icon.svg"
  avatar = "https://avatars.githubusercontent.com/u/46620366"

  [[params.links]]
    title = "My-Organization"
    href = "https://github.com/my-org"
    icon = "https://via.placeholder.com/32" # 조직의 로고 이미지 URL

  [[params.links]]
    title = "Another-Org"
    href = "https://github.com/another-org"
    icon = "/images/another-org-icon.png" # static/images/ 에 위치한 아이콘

# Hugo Mounts Configuration
[[module.mounts]]
source = "content/About-218dcd44779f81169bcedf9476baf73b.md"
target = "content/readme.md"

[[module.mounts]]
source = "content/posts"
target = "content/post"
